---
roles:
  - src: stackhpc.nfs
  - name: stackhpc.openhpc
    src: https://github.com/stackhpc/ansible-role-openhpc
    type: git
    version: v0.10.0
  #- src: cloudalchemy.node_exporter
  - src: https://github.com/stackhpc/ansible-node-exporter.git
    name: cloudalchemy.node_exporter
    version: support-rhel-clones # Fixes for Rocky
  - src: cloudalchemy.blackbox-exporter
  #- src: cloudalchemy.prometheus
  - src: https://github.com/cloudalchemy/ansible-prometheus.git
    name: cloudalchemy.prometheus
    version: 0795bdb1a5a424044dc7e8200129f61e53140523 # Fixes for Rocky
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: jriguera.configdrive
  - name: stackhpc.terraform-infra
    src: https://github.com/stackhpc/ansible-role-terraform-infra
    type: git
    version: 4d9d67b5a1866edf6988a1f7e9e64868df8f65ae

collections:
  - name: ansible.posix
  - name: ansible.netcommon
  - name: community.general
    # Pegged at 4.5.0 due to https://github.com/ansible-collections/community.general/pull/4281
    version: 4.5.0
  - name: community.grafana
  - name: community.mysql
  - name: containers.podman
  - name: openstack.cloud
  - name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
    type: git
    version: v0.1.0
