---
roles:
  - src: stackhpc.nfs
    version: v22.9.1
  - src: https://github.com/stackhpc/ansible-role-openhpc.git
    version: v0.16.0
    name: stackhpc.openhpc
  - src: https://github.com/stackhpc/ansible-node-exporter.git
    version: feature/no-install
    name: cloudalchemy.node_exporter
  - src: cloudalchemy.blackbox-exporter
    version: 1.0.0
  - src: https://github.com/cloudalchemy/ansible-prometheus.git
    version: 4d2c8d742de39e50387e0aa6d5510b21c7451343 # need fix in preceeding commit for rocky
    name: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
    version: 0.19.1
  - src: https://github.com/stackhpc/ansible-grafana.git
    name: cloudalchemy.grafana
    version: service-state
  - src: jriguera.configdrive
  # No versions available
  - src: https://github.com/OSC/ood-ansible.git
    name: osc.ood
    version: v2.0.5

collections:
  - name: containers.podman
  - name: community.grafana
  - name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
    type: git
    version: v0.2.0
  - name: ansible.posix
  - name: ansible.netcommon
  - name: community.general
    version: 4.5.0  # https://github.com/ansible-collections/community.general/pull/4281

  - name: community.mysql

  - name: openstack.cloud
  - name: https://github.com/stackhpc/ansible-collection-terraform
    type: git
    version: 75fb75132bbc77e3e78a05ba674458131da2b1dd
    